"""
Curated ESG metric catalog — sourced from GRI Universal Standards, SASB
cross-industry and sector-specific standards, and CDP questionnaires.

Structure:
  METRIC_DEFINITIONS  — master list of all metrics (dicts)
  SECTOR_METRICS      — sector key → list of metric keys that apply
  SASB_SECTORS        — valid sector keys the LLM must choose from
"""

# ---------------------------------------------------------------------------
# Master metric registry
# ---------------------------------------------------------------------------

METRIC_DEFINITIONS = [

    # -----------------------------------------------------------------------
    # UNIVERSAL — Sustainalytics / yfinance ESG Scores
    # Populated when a company has a public listing and Yahoo Finance has data.
    # -----------------------------------------------------------------------
    {
        "key": "sustainalytics_total_esg_score",
        "name": "Sustainalytics Total ESG Risk Score",
        "description": "Overall ESG risk score from Sustainalytics via Yahoo Finance (lower = less risk)",
        "unit": "risk score (0-100)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Sustainalytics",
        "is_universal": True,
    },
    {
        "key": "sustainalytics_environment_score",
        "name": "Sustainalytics Environment Score",
        "description": "Environmental sub-score from Sustainalytics",
        "unit": "risk score (0-100)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Sustainalytics",
        "is_universal": True,
    },
    {
        "key": "sustainalytics_social_score",
        "name": "Sustainalytics Social Score",
        "description": "Social sub-score from Sustainalytics",
        "unit": "risk score (0-100)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Sustainalytics",
        "is_universal": True,
    },
    {
        "key": "sustainalytics_governance_score",
        "name": "Sustainalytics Governance Score",
        "description": "Governance sub-score from Sustainalytics",
        "unit": "risk score (0-100)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Sustainalytics",
        "is_universal": True,
    },
    {
        "key": "sustainalytics_controversy_level",
        "name": "Sustainalytics Controversy Level",
        "description": "Highest controversy level (1–5) flagged by Sustainalytics",
        "unit": "level (1-5)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Sustainalytics",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # UNIVERSAL — Environmental
    # -----------------------------------------------------------------------
    {
        "key": "scope_1_emissions",
        "name": "Scope 1 GHG Emissions",
        "description": "Direct greenhouse gas emissions from company-owned and controlled sources",
        "unit": "tCO2e",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 305-1",
        "is_universal": True,
    },
    {
        "key": "scope_2_emissions",
        "name": "Scope 2 GHG Emissions",
        "description": "Indirect GHG emissions from purchased electricity, steam, heat, or cooling",
        "unit": "tCO2e",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 305-2",
        "is_universal": True,
    },
    {
        "key": "scope_3_emissions",
        "name": "Scope 3 GHG Emissions",
        "description": "All other indirect GHG emissions in the value chain",
        "unit": "tCO2e",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 305-3",
        "is_universal": True,
    },
    {
        "key": "total_energy_consumption",
        "name": "Total Energy Consumption",
        "description": "Total energy consumed from all sources including fuel and electricity",
        "unit": "GJ",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 302-1",
        "is_universal": True,
    },
    {
        "key": "renewable_energy_pct",
        "name": "Renewable Energy Percentage",
        "description": "Share of total energy consumption from renewable sources",
        "unit": "%",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 302-1",
        "is_universal": True,
    },
    {
        "key": "water_withdrawal",
        "name": "Total Water Withdrawal",
        "description": "Total volume of water drawn from all sources",
        "unit": "m3",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 303-3",
        "is_universal": True,
    },
    {
        "key": "total_waste_generated",
        "name": "Total Waste Generated",
        "description": "Total weight of waste generated, split by hazardous and non-hazardous",
        "unit": "tonnes",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "GRI 306-3",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # UNIVERSAL — Social
    # -----------------------------------------------------------------------
    {
        "key": "employee_count",
        "name": "Total Employees",
        "description": "Total number of employees at end of reporting period",
        "unit": "#",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 2-7",
        "is_universal": True,
    },
    {
        "key": "annual_revenue",
        "name": "Annual Revenue",
        "description": "Total annual revenue — context metric used as the denominator for emission/resource intensity (carbon-per-revenue)",
        "unit": "USD millions",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Financials",
        "is_universal": True,
    },
    {
        "key": "female_employees_pct",
        "name": "Female Employees Percentage",
        "description": "Percentage of total workforce that identifies as female",
        "unit": "%",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 405-1",
        "is_universal": True,
    },
    {
        "key": "female_board_pct",
        "name": "Female Board Members Percentage",
        "description": "Percentage of board of directors that identifies as female",
        "unit": "%",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 405-1",
        "is_universal": True,
    },
    {
        "key": "employee_turnover_rate",
        "name": "Employee Turnover Rate",
        "description": "Percentage of employees who left the organization during the reporting period",
        "unit": "%",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 401-1",
        "is_universal": True,
    },
    {
        "key": "lost_time_injury_rate",
        "name": "Lost Time Injury Rate",
        "description": "Number of lost time injuries per 200,000 hours worked",
        "unit": "per 200k hours",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 403-9",
        "is_universal": True,
    },
    {
        "key": "training_hours_per_employee",
        "name": "Average Training Hours per Employee",
        "description": "Average hours of training and development per employee per year",
        "unit": "hours",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 404-1",
        "is_universal": True,
    },
    {
        "key": "living_wage_commitment",
        "name": "Living Wage Commitment",
        "description": "Whether the company commits to paying a living wage to all employees",
        "unit": "Yes/No",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "GRI 202-1",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # UNIVERSAL — Governance
    # -----------------------------------------------------------------------
    {
        "key": "board_independence_pct",
        "name": "Board Independence Percentage",
        "description": "Percentage of board members who are independent non-executive directors",
        "unit": "%",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 2-9",
        "is_universal": True,
    },
    {
        "key": "ceo_pay_ratio",
        "name": "CEO-to-Median Worker Pay Ratio",
        "description": "Ratio of CEO total compensation to median employee total compensation",
        "unit": "x:1 ratio",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 2-21",
        "is_universal": True,
    },
    {
        "key": "anti_corruption_policy",
        "name": "Anti-Corruption Policy",
        "description": "Whether the company has a formal, publicly available anti-corruption policy",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 205-2",
        "is_universal": True,
    },
    {
        "key": "whistleblower_mechanism",
        "name": "Whistleblower Mechanism",
        "description": "Whether the company has a formal anonymous whistleblower reporting channel",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 2-26",
        "is_universal": True,
    },
    {
        "key": "esg_report_published",
        "name": "ESG / Sustainability Report Published",
        "description": "Whether the company published a standalone ESG or sustainability report this year",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 2-3",
        "is_universal": True,
    },
    {
        "key": "third_party_esg_audit",
        "name": "Third-Party ESG Data Assurance",
        "description": "Whether ESG disclosures have been externally verified or assured",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "GRI 2-5",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # SOURCE — B Corp Impact Scores
    # Normalised to 0-100 (raw B Corp scale is 0-200, halved on ingest).
    # -----------------------------------------------------------------------
    {
        "key": "bcorp_overall_score",
        "name": "B Corp Overall Impact Score",
        "description": "Overall B Impact Assessment score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },
    {
        "key": "bcorp_environment_score",
        "name": "B Corp Environment Score",
        "description": "B Impact Assessment environment pillar score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },
    {
        "key": "bcorp_workers_score",
        "name": "B Corp Workers Score",
        "description": "B Impact Assessment workers pillar score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },
    {
        "key": "bcorp_community_score",
        "name": "B Corp Community Score",
        "description": "B Impact Assessment community pillar score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },
    {
        "key": "bcorp_customers_score",
        "name": "B Corp Customers Score",
        "description": "B Impact Assessment customers pillar score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },
    {
        "key": "bcorp_governance_score",
        "name": "B Corp Governance Score",
        "description": "B Impact Assessment governance pillar score, normalised to 0-100",
        "unit": "score (0-100)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "B Lab BIA",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # SOURCE — Upright Platform Net Impact Scores
    # Values are cents per dollar of revenue (can be negative = harm).
    # -----------------------------------------------------------------------
    {
        "key": "upright_net_impact_ratio",
        "name": "Upright Net Impact Ratio",
        "description": "Net societal impact per dollar of revenue (negative = net harm, positive = net benefit)",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_net_impact_percentile",
        "name": "Upright Net Impact Percentile",
        "description": "Percentile rank among 10,000+ companies (higher = more positive impact)",
        "unit": "percentile (0-100)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_ghg_negative",
        "name": "Upright GHG Emissions Cost",
        "description": "GHG emissions impact cost in cents per dollar of revenue (harm)",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_ghg_positive",
        "name": "Upright GHG Emissions Benefit",
        "description": "GHG emissions avoided — benefit in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_non_ghg_negative",
        "name": "Upright Non-GHG Air Pollution Cost",
        "description": "Non-GHG air pollution impact in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_scarce_resources",
        "name": "Upright Scarce Natural Resources Impact",
        "description": "Scarce natural resources consumption cost in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_biodiversity_negative",
        "name": "Upright Biodiversity Impact",
        "description": "Biodiversity loss impact in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_waste_negative",
        "name": "Upright Waste Impact",
        "description": "Waste generation impact cost in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_jobs_positive",
        "name": "Upright Jobs Benefit",
        "description": "Jobs created benefit in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_taxes_positive",
        "name": "Upright Taxes Benefit",
        "description": "Tax contribution benefit in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "G",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_equality_negative",
        "name": "Upright Equality & Human Rights Cost",
        "description": "Equality and human rights harm in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_equality_positive",
        "name": "Upright Equality & Human Rights Benefit",
        "description": "Equality and human rights benefit in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_health_negative",
        "name": "Upright Physical Health Cost",
        "description": "Physical disease impact cost in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_health_positive",
        "name": "Upright Physical Health Benefit",
        "description": "Physical health benefit in cents per dollar of revenue",
        "unit": "monetised impact (USD/USD revenue)",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_sdg_13_climate",
        "name": "Upright SDG 13 Climate Action Alignment",
        "description": "Degree of alignment with SDG 13 (Climate Action)",
        "unit": "0-1 index",
        "category": "E",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_sdg_8_decent_work",
        "name": "Upright SDG 8 Decent Work Alignment",
        "description": "Degree of alignment with SDG 8 (Decent Work and Economic Growth)",
        "unit": "0-1 index",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },
    {
        "key": "upright_sdg_5_gender",
        "name": "Upright SDG 5 Gender Equality Alignment",
        "description": "Degree of alignment with SDG 5 (Gender Equality)",
        "unit": "0-1 index",
        "category": "S",
        "sasb_sector": None,
        "source_framework": "Upright Platform",
        "is_universal": True,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Agriculture & Food
    # -----------------------------------------------------------------------
    {
        "key": "pesticide_use",
        "name": "Pesticide Use",
        "description": "Total weight of pesticides applied per unit of crop area",
        "unit": "kg/hectare",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-160a.1",
        "is_universal": False,
    },
    {
        "key": "sustainable_sourcing_pct",
        "name": "Sustainably Sourced Raw Materials",
        "description": "Percentage of key raw materials sourced from certified sustainable suppliers",
        "unit": "%",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-430a.1",
        "is_universal": False,
    },
    {
        "key": "food_safety_incidents",
        "name": "Food Safety Incidents",
        "description": "Number of recalls, withdrawals, or regulatory actions related to food safety",
        "unit": "#",
        "category": "S",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-250a.2",
        "is_universal": False,
    },
    {
        "key": "land_use",
        "name": "Total Land Use",
        "description": "Total area of land owned, leased, or managed for production",
        "unit": "hectares",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-160a.2",
        "is_universal": False,
    },
    {
        "key": "water_stress_exposure_pct",
        "name": "Operations in Water-Stressed Areas",
        "description": "Percentage of production facilities or land in high water-stress regions",
        "unit": "%",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-140a.1",
        "is_universal": False,
    },
    {
        "key": "food_waste_pct",
        "name": "Food Loss and Waste",
        "description": "Food waste as a percentage of total production volume",
        "unit": "%",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "GRI 306-3",
        "is_universal": False,
    },
    {
        "key": "packaging_recyclable_pct",
        "name": "Recyclable or Reusable Packaging",
        "description": "Percentage of total packaging that is recyclable, reusable, or compostable",
        "unit": "%",
        "category": "E",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-410a.1",
        "is_universal": False,
    },
    {
        "key": "animal_welfare_policy",
        "name": "Animal Welfare Policy",
        "description": "Whether the company has a formal, publicly available animal welfare policy",
        "unit": "Yes/No",
        "category": "S",
        "sasb_sector": "agriculture_food",
        "source_framework": "SASB FB-AG-270a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Apparel & Retail
    # -----------------------------------------------------------------------
    {
        "key": "supplier_audit_coverage_pct",
        "name": "Supplier Audit Coverage",
        "description": "Percentage of Tier 1 suppliers audited for social and environmental compliance",
        "unit": "%",
        "category": "S",
        "sasb_sector": "apparel_retail",
        "source_framework": "SASB CG-AA-430a.1",
        "is_universal": False,
    },
    {
        "key": "conflict_minerals_policy",
        "name": "Conflict Minerals Policy",
        "description": "Whether the company has a formal policy on conflict minerals (3TG)",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": "apparel_retail",
        "source_framework": "SASB CG-AA-430a.2",
        "is_universal": False,
    },
    {
        "key": "product_take_back_pct",
        "name": "Products Taken Back for Recycling",
        "description": "Percentage of products recovered through take-back or recycling programs",
        "unit": "%",
        "category": "E",
        "sasb_sector": "apparel_retail",
        "source_framework": "SASB CG-AA-410a.1",
        "is_universal": False,
    },
    {
        "key": "sustainable_materials_pct",
        "name": "Sustainable or Recycled Input Materials",
        "description": "Percentage of raw materials sourced from recycled or sustainably certified sources",
        "unit": "%",
        "category": "E",
        "sasb_sector": "apparel_retail",
        "source_framework": "SASB CG-AA-440a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Chemicals
    # -----------------------------------------------------------------------
    {
        "key": "hazardous_waste_generated",
        "name": "Hazardous Waste Generated",
        "description": "Total weight of hazardous waste generated",
        "unit": "tonnes",
        "category": "E",
        "sasb_sector": "chemicals",
        "source_framework": "SASB RT-CH-150a.1",
        "is_universal": False,
    },
    {
        "key": "process_safety_incidents",
        "name": "Process Safety Incidents",
        "description": "Number of Tier 1 process safety incidents (releases, fires, explosions)",
        "unit": "#",
        "category": "S",
        "sasb_sector": "chemicals",
        "source_framework": "SASB RT-CH-540a.1",
        "is_universal": False,
    },
    {
        "key": "r_and_d_sustainable_pct",
        "name": "R&D Spend on Sustainable Chemistry",
        "description": "Percentage of R&D expenditure directed at green or sustainable chemistry products",
        "unit": "%",
        "category": "E",
        "sasb_sector": "chemicals",
        "source_framework": "SASB RT-CH-410a.1",
        "is_universal": False,
    },
    {
        "key": "chemical_safety_data_sheets_pct",
        "name": "Products with Safety Data Sheets",
        "description": "Percentage of products for which a Safety Data Sheet is publicly available",
        "unit": "%",
        "category": "S",
        "sasb_sector": "chemicals",
        "source_framework": "SASB RT-CH-250a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Construction & Real Estate
    # -----------------------------------------------------------------------
    {
        "key": "green_building_pct",
        "name": "Green Certified Buildings",
        "description": "Percentage of floor area with green building certification (LEED, BREEAM, etc.)",
        "unit": "%",
        "category": "E",
        "sasb_sector": "construction",
        "source_framework": "SASB IF-RE-410a.1",
        "is_universal": False,
    },
    {
        "key": "building_energy_intensity",
        "name": "Building Energy Intensity",
        "description": "Average energy consumption per square metre of managed floor area",
        "unit": "kWh/m2",
        "category": "E",
        "sasb_sector": "construction",
        "source_framework": "SASB IF-RE-130a.1",
        "is_universal": False,
    },
    {
        "key": "construction_waste_recycled_pct",
        "name": "Construction Waste Diverted from Landfill",
        "description": "Percentage of construction and demolition waste recycled or reused",
        "unit": "%",
        "category": "E",
        "sasb_sector": "construction",
        "source_framework": "SASB IF-RE-150a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Extractives & Mining
    # -----------------------------------------------------------------------
    {
        "key": "methane_emissions_intensity",
        "name": "Methane Emissions Intensity",
        "description": "Methane emissions per unit of production (BOE or tonne of output)",
        "unit": "tCO2e/BOE",
        "category": "E",
        "sasb_sector": "extractives",
        "source_framework": "SASB EM-EP-110a.1",
        "is_universal": False,
    },
    {
        "key": "hydrocarbon_spill_volume",
        "name": "Volume of Hydrocarbon Spills",
        "description": "Total volume of hydrocarbon spills to the environment",
        "unit": "barrels",
        "category": "E",
        "sasb_sector": "extractives",
        "source_framework": "SASB EM-EP-167a.1",
        "is_universal": False,
    },
    {
        "key": "flared_gas_volume",
        "name": "Flared Gas Volume",
        "description": "Total volume of natural gas flared at production sites",
        "unit": "MMcf",
        "category": "E",
        "sasb_sector": "extractives",
        "source_framework": "SASB EM-EP-110a.2",
        "is_universal": False,
    },
    {
        "key": "mine_safety_incidents",
        "name": "Mine Safety Incidents",
        "description": "Total recordable incident rate (TRIR) for mining operations",
        "unit": "per 200k hours",
        "category": "S",
        "sasb_sector": "extractives",
        "source_framework": "SASB EM-MM-540a.1",
        "is_universal": False,
    },
    {
        "key": "land_disturbed_reclaimed_ratio",
        "name": "Land Disturbed vs Reclaimed Ratio",
        "description": "Ratio of land disturbed by operations to land successfully reclaimed",
        "unit": "ratio (0-1)",
        "category": "E",
        "sasb_sector": "extractives",
        "source_framework": "SASB EM-MM-160a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Financial Services
    # -----------------------------------------------------------------------
    {
        "key": "financed_emissions",
        "name": "Financed Emissions",
        "description": "GHG emissions attributable to loans and investments in the portfolio",
        "unit": "tCO2e",
        "category": "E",
        "sasb_sector": "financials",
        "source_framework": "PCAF / SASB FN-CB-410a.1",
        "is_universal": False,
    },
    {
        "key": "climate_risk_exposure_pct",
        "name": "Climate Risk Exposed Portfolio",
        "description": "Percentage of loan or investment portfolio exposed to high climate risk sectors",
        "unit": "%",
        "category": "E",
        "sasb_sector": "financials",
        "source_framework": "SASB FN-CB-450a.1",
        "is_universal": False,
    },
    {
        "key": "financial_inclusion_products",
        "name": "Financial Inclusion Products",
        "description": "Number of products or programs designed for underserved or unbanked populations",
        "unit": "#",
        "category": "S",
        "sasb_sector": "financials",
        "source_framework": "SASB FN-CB-240a.1",
        "is_universal": False,
    },
    {
        "key": "data_security_breaches",
        "name": "Customer Data Security Breaches",
        "description": "Number of data breaches involving customer personal or financial data",
        "unit": "#",
        "category": "G",
        "sasb_sector": "financials",
        "source_framework": "SASB FN-CB-230a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Healthcare
    # -----------------------------------------------------------------------
    {
        "key": "patient_safety_incidents",
        "name": "Patient Safety Incidents",
        "description": "Number of reportable patient safety events or adverse incidents",
        "unit": "#",
        "category": "S",
        "sasb_sector": "healthcare",
        "source_framework": "SASB HC-DY-250a.1",
        "is_universal": False,
    },
    {
        "key": "medical_device_recalls",
        "name": "Medical Device / Product Recalls",
        "description": "Number of product recalls or field safety corrective actions issued",
        "unit": "#",
        "category": "S",
        "sasb_sector": "healthcare",
        "source_framework": "SASB HC-MS-250a.1",
        "is_universal": False,
    },
    {
        "key": "clinical_trial_transparency",
        "name": "Clinical Trial Transparency",
        "description": "Whether the company registers all trials and publishes results regardless of outcome",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": "healthcare",
        "source_framework": "SASB HC-BP-240a.2",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Pharmaceuticals & Biotech
    # -----------------------------------------------------------------------
    {
        "key": "r_and_d_spend_pct",
        "name": "R&D Spend as % of Revenue",
        "description": "Research and development expenditure as a percentage of total revenue",
        "unit": "%",
        "category": "G",
        "sasb_sector": "pharmaceuticals",
        "source_framework": "SASB HC-BP-240a.1",
        "is_universal": False,
    },
    {
        "key": "drug_pricing_transparency",
        "name": "Drug Pricing Transparency",
        "description": "Whether the company publicly discloses its methodology for setting drug prices",
        "unit": "Yes/No",
        "category": "G",
        "sasb_sector": "pharmaceuticals",
        "source_framework": "SASB HC-BP-240a.3",
        "is_universal": False,
    },
    {
        "key": "access_to_medicine_pct",
        "name": "Products Available in Low-Income Markets",
        "description": "Percentage of product portfolio available in least-developed or low-income countries",
        "unit": "%",
        "category": "S",
        "sasb_sector": "pharmaceuticals",
        "source_framework": "SASB HC-BP-240a.4",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Technology
    # -----------------------------------------------------------------------
    {
        "key": "customer_data_breaches",
        "name": "Customer Data Breaches",
        "description": "Number of data breaches or cybersecurity incidents involving customer data",
        "unit": "#",
        "category": "G",
        "sasb_sector": "technology",
        "source_framework": "SASB TC-SI-230a.1",
        "is_universal": False,
    },
    {
        "key": "product_energy_efficiency_improvement",
        "name": "Product Energy Efficiency Improvement",
        "description": "Year-over-year improvement in energy efficiency of flagship products",
        "unit": "%",
        "category": "E",
        "sasb_sector": "technology",
        "source_framework": "SASB TC-HW-410a.1",
        "is_universal": False,
    },
    {
        "key": "e_waste_recycled",
        "name": "E-Waste Recycled",
        "description": "Weight of electronic waste recovered and recycled through take-back programs",
        "unit": "tonnes",
        "category": "E",
        "sasb_sector": "technology",
        "source_framework": "SASB TC-HW-150a.1",
        "is_universal": False,
    },
    {
        "key": "data_center_pue",
        "name": "Data Centre Power Usage Effectiveness (PUE)",
        "description": "Average PUE across all owned and operated data centres (lower is better)",
        "unit": "ratio (>=1.0)",
        "category": "E",
        "sasb_sector": "technology",
        "source_framework": "SASB TC-SI-130a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Transportation
    # -----------------------------------------------------------------------
    {
        "key": "fleet_fuel_efficiency",
        "name": "Fleet Fuel Efficiency",
        "description": "Average fuel efficiency of the operated vehicle or aircraft fleet",
        "unit": "L/100km or MPG",
        "category": "E",
        "sasb_sector": "transportation",
        "source_framework": "SASB TR-RA-110a.1",
        "is_universal": False,
    },
    {
        "key": "nox_sox_emissions",
        "name": "NOx and SOx Emissions",
        "description": "Total nitrogen and sulphur oxide emissions from operations",
        "unit": "tonnes",
        "category": "E",
        "sasb_sector": "transportation",
        "source_framework": "SASB TR-RA-110a.2",
        "is_universal": False,
    },
    {
        "key": "transport_safety_incidents",
        "name": "Safety Incidents per Million Miles",
        "description": "Number of reportable safety incidents per million miles/kilometres operated",
        "unit": "per million miles",
        "category": "S",
        "sasb_sector": "transportation",
        "source_framework": "SASB TR-RA-540a.1",
        "is_universal": False,
    },
    {
        "key": "fleet_ev_pct",
        "name": "Electric / Low-Emission Vehicles in Fleet",
        "description": "Percentage of fleet that is fully electric or meets low-emission standards",
        "unit": "%",
        "category": "E",
        "sasb_sector": "transportation",
        "source_framework": "SASB TR-RA-410a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Utilities
    # -----------------------------------------------------------------------
    {
        "key": "grid_reliability_saidi",
        "name": "Grid Reliability — SAIDI",
        "description": "System Average Interruption Duration Index: average outage duration per customer per year",
        "unit": "minutes",
        "category": "S",
        "sasb_sector": "utilities",
        "source_framework": "SASB IF-EU-550a.1",
        "is_universal": False,
    },
    {
        "key": "transmission_losses_pct",
        "name": "Transmission and Distribution Losses",
        "description": "Percentage of electricity lost in transmission and distribution networks",
        "unit": "%",
        "category": "E",
        "sasb_sector": "utilities",
        "source_framework": "SASB IF-EU-000.B",
        "is_universal": False,
    },
    {
        "key": "water_treatment_capacity",
        "name": "Water Treatment Capacity",
        "description": "Maximum daily water treatment or supply capacity",
        "unit": "m3/day",
        "category": "E",
        "sasb_sector": "utilities",
        "source_framework": "SASB IF-WU-000.A",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Media & Telecommunications
    # -----------------------------------------------------------------------
    {
        "key": "data_privacy_complaints",
        "name": "Data Privacy Complaints",
        "description": "Number of substantiated complaints received from customers regarding data privacy",
        "unit": "#",
        "category": "G",
        "sasb_sector": "media_telecom",
        "source_framework": "SASB TC-TL-220a.1",
        "is_universal": False,
    },
    {
        "key": "network_uptime_pct",
        "name": "Network Uptime / Availability",
        "description": "Percentage of time the core network was available during the reporting period",
        "unit": "%",
        "category": "S",
        "sasb_sector": "media_telecom",
        "source_framework": "SASB TC-TL-550a.1",
        "is_universal": False,
    },
    {
        "key": "digital_inclusion_programs",
        "name": "Digital Inclusion Programs",
        "description": "Number of active programs improving connectivity or digital literacy for underserved communities",
        "unit": "#",
        "category": "S",
        "sasb_sector": "media_telecom",
        "source_framework": "SASB TC-TL-240a.1",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Professional & Consumer Services
    # -----------------------------------------------------------------------
    {
        "key": "supplier_diversity_pct",
        "name": "Diverse Supplier Spend",
        "description": "Percentage of procurement spend with minority, women, or veteran-owned businesses",
        "unit": "%",
        "category": "S",
        "sasb_sector": "services",
        "source_framework": "GRI 204-1",
        "is_universal": False,
    },
    {
        "key": "employee_benefit_coverage_pct",
        "name": "Employee Benefits Coverage",
        "description": "Percentage of full-time employees covered by health, retirement, and wellness benefits",
        "unit": "%",
        "category": "S",
        "sasb_sector": "services",
        "source_framework": "GRI 401-2",
        "is_universal": False,
    },

    # -----------------------------------------------------------------------
    # SECTOR — Consumer Goods
    # -----------------------------------------------------------------------
    {
        "key": "product_safety_incidents",
        "name": "Product Safety Incidents and Recalls",
        "description": "Number of product recalls or safety incidents reported to regulators",
        "unit": "#",
        "category": "S",
        "sasb_sector": "consumer_goods",
        "source_framework": "SASB CG-HP-250a.1",
        "is_universal": False,
    },
    {
        "key": "sustainable_packaging_pct",
        "name": "Sustainable Packaging",
        "description": "Percentage of total packaging weight that meets sustainability criteria",
        "unit": "%",
        "category": "E",
        "sasb_sector": "consumer_goods",
        "source_framework": "SASB CG-HP-410a.1",
        "is_universal": False,
    },
    {
        "key": "tier1_supplier_transparency_pct",
        "name": "Tier 1 Supplier Transparency",
        "description": "Percentage of Tier 1 suppliers publicly disclosed on the company website",
        "unit": "%",
        "category": "G",
        "sasb_sector": "consumer_goods",
        "source_framework": "GRI 2-6",
        "is_universal": False,
    },
]


# ---------------------------------------------------------------------------
# Sector → specific metric keys
# (universal metrics are always added on top of these)
# ---------------------------------------------------------------------------

SECTOR_METRICS: dict[str, list[str]] = {
    "agriculture_food": [
        "pesticide_use",
        "sustainable_sourcing_pct",
        "food_safety_incidents",
        "land_use",
        "water_stress_exposure_pct",
        "food_waste_pct",
        "packaging_recyclable_pct",
        "animal_welfare_policy",
    ],
    "apparel_retail": [
        "supplier_audit_coverage_pct",
        "conflict_minerals_policy",
        "product_take_back_pct",
        "sustainable_materials_pct",
    ],
    "chemicals": [
        "hazardous_waste_generated",
        "process_safety_incidents",
        "r_and_d_sustainable_pct",
        "chemical_safety_data_sheets_pct",
    ],
    "construction": [
        "green_building_pct",
        "building_energy_intensity",
        "construction_waste_recycled_pct",
    ],
    "consumer_goods": [
        "product_safety_incidents",
        "sustainable_packaging_pct",
        "tier1_supplier_transparency_pct",
    ],
    "extractives": [
        "methane_emissions_intensity",
        "hydrocarbon_spill_volume",
        "flared_gas_volume",
        "mine_safety_incidents",
        "land_disturbed_reclaimed_ratio",
    ],
    "financials": [
        "financed_emissions",
        "climate_risk_exposure_pct",
        "financial_inclusion_products",
        "data_security_breaches",
    ],
    "healthcare": [
        "patient_safety_incidents",
        "medical_device_recalls",
        "clinical_trial_transparency",
    ],
    "pharmaceuticals": [
        "r_and_d_spend_pct",
        "drug_pricing_transparency",
        "access_to_medicine_pct",
    ],
    "technology": [
        "customer_data_breaches",
        "product_energy_efficiency_improvement",
        "e_waste_recycled",
        "data_center_pue",
    ],
    "transportation": [
        "fleet_fuel_efficiency",
        "nox_sox_emissions",
        "transport_safety_incidents",
        "fleet_ev_pct",
    ],
    "utilities": [
        "grid_reliability_saidi",
        "transmission_losses_pct",
        "water_treatment_capacity",
    ],
    "media_telecom": [
        "data_privacy_complaints",
        "network_uptime_pct",
        "digital_inclusion_programs",
    ],
    "services": [
        "supplier_diversity_pct",
        "employee_benefit_coverage_pct",
    ],
    "general": [],  # universal metrics only
}

# Valid sector keys the LLM must choose from
SASB_SECTORS = list(SECTOR_METRICS.keys())
