"""
governance_regimes_verified.py — AUTO-GENERATED by
scripts/verify_governance_regimes.py. Do not hand-edit; re-run the script.

Each entry was extracted from a live web search for that country's own
corporate-governance code and securities regulator, then filtered to
reject generic boilerplate ('corporate governance code' on its own) and
any phrase naming a different country. Entries are therefore evidence-
backed rather than authored, but they are STILL machine-extracted: treat
them as query hints, not as authoritative legal citations.

Countries with a hand-written profile in country_governance_keywords.py
take precedence over anything here -- those were written deliberately.
"""

VERIFIED_REGIMES: dict[str, tuple[str, ...]] = {
    'ARE': ('The UAE Corporate Governance Code', 'Corporate Governance Standards',),  # United Arab Emirates
    'ARM': ('State Securities Commission', 'Financial Markets Authority',),  # Armenia
    'AUT': ('The Austrian Corporate Governance Code',),  # Austria
    'EGY': ('Egyptian Financial Supervisory Authority', 'The Financial Supervisory Authority', 'The Egyptian Financial Supervisory Authority',),  # Egypt
    'NGA': ("Central Bank of Nigeria's",),  # Nigeria
    'PER': ('Financial Supervisory Authority',),  # Peru
    'POL': ('Polish Financial Supervisory Authority',),  # Poland
    'VNM': ('The Viet Nam Corporate Governance Code', 'Vietnam Corporate Governance Code', 'Financial Supervisory Commission',),  # Vietnam
}
